### ISSUE TITLE
Not Windows Compatible 

### ISSUE THREAD

**Issue by thyngs** [carlosthe19916/cra-typescript-storybook#1]
I've been fiddling with this repo for a while as I like the idea of it, but unfortunately it appears to be incompatible with Windows machines.

**Comment by carlosthe19916** [comment]
Hi @thyngs. Unfortunately, I don't use Windows so I can not test this repository as easily as I'd like.
Could you let me know what you want to achieve?
- Do you want just storybooks?
- Do you want to publish your library to npm?
- Or do you want all together: storybooks, publish to npm, and have your working UI project in the same repository?

**Comment by thyngs** [comment]
I generally don't use a Windows machine either, but with a bit of digging I managed to get it working by installing 'cross-env' with NPM and prefixing the lines in the following scripts 'build:babel:cjs', 'build:babel:esm", "build:babel:umd" with 'cross-env '. Thanks for your great hard work.
